[package]
name = "chainbridge_kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
lazy_static = "1.5.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
